
INSERT INTO `countries` (`id`, `nombre`, `name`, `nom`, `iso2`, `iso3`, `phone_code`) VALUES
(1, 'nombre', ' name', ' nom', ' iso2', ' iso3', ' phone_code'),
(2, 'Afganistán', 'Afghanistan', 'Afghanistan', 'AF', 'AFG', '93'),
(3, 'Albania', 'Albania', 'Albanie', 'AL', 'ALB', '355'),
(4, 'Alemania', 'Germany', 'Allemagne', 'DE', 'DEU', '49'),
(5, 'Andorra', 'Andorra', 'Andorra', 'AD', 'AND', '376'),
(6, 'Angola', 'Angola', 'Angola', 'AO', 'AGO', '244'),
(7, 'Anguila', 'Anguilla', 'Anguilla', 'AI', 'AIA', '1 264'),
(8, 'Antártida', 'Antarctica', 'L\'Antarctique', 'AQ', 'ATA', '672'),
(9, 'Antigua y Barbuda', 'Antigua and Barbuda', 'Antigua et Barbuda', 'AG', 'ATG', '1 268'),
(10, 'Arabia Saudita', 'Saudi Arabia', 'Arabie Saoudite', 'SA', 'SAU', '966'),
(11, 'Argelia', 'Algeria', 'Algérie', 'DZ', 'DZA', '213'),
(12, 'Argentina', 'Argentina', 'Argentine', 'AR', 'ARG', '54'),
(13, 'Armenia', 'Armenia', 'L\'Arménie', 'AM', 'ARM', '374'),
(14, 'Aruba', 'Aruba', 'Aruba', 'AW', 'ABW', '297'),
(15, 'Australia', 'Australia', 'Australie', 'AU', 'AUS', '61'),
(16, 'Austria', 'Austria', 'Autriche', 'AT', 'AUT', '43'),
(17, 'Azerbaiyán', 'Azerbaijan', 'L\'Azerbaïdjan', 'AZ', 'AZE', '994'),
(18, 'Bélgica', 'Belgium', 'Belgique', 'BE', 'BEL', '32'),
(19, 'Bahamas', 'Bahamas', 'Bahamas', 'BS', 'BHS', '1 242'),
(20, 'Bahrein', 'Bahrain', 'Bahreïn', 'BH', 'BHR', '973'),
(21, 'Bangladesh', 'Bangladesh', 'Bangladesh', 'BD', 'BGD', '880'),
(22, 'Barbados', 'Barbados', 'Barbade', 'BB', 'BRB', '1 246'),
(23, 'Belice', 'Belize', 'Belize', 'BZ', 'BLZ', '501'),
(24, 'Benín', 'Benin', 'Bénin', 'BJ', 'BEN', '229'),
(25, 'Bhután', 'Bhutan', 'Le Bhoutan', 'BT', 'BTN', '975'),
(26, 'Bielorrusia', 'Belarus', 'Biélorussie', 'BY', 'BLR', '375'),
(27, 'Birmania', 'Myanmar', 'Myanmar', 'MM', 'MMR', '95'),
(28, 'Bolivia', 'Bolivia', 'Bolivie', 'BO', 'BOL', '591'),
(29, 'Bosnia y Herzegovina', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'BA', 'BIH', '387'),
(30, 'Botsuana', 'Botswana', 'Botswana', 'BW', 'BWA', '267'),
(31, 'Brasil', 'Brazil', 'Brésil', 'BR', 'BRA', '55'),
(32, 'Brunéi', 'Brunei', 'Brunei', 'BN', 'BRN', '673'),
(33, 'Bulgaria', 'Bulgaria', 'Bulgarie', 'BG', 'BGR', '359'),
(34, 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '226'),
(35, 'Burundi', 'Burundi', 'Burundi', 'BI', 'BDI', '257'),
(36, 'Cabo Verde', 'Cape Verde', 'Cap-Vert', 'CV', 'CPV', '238'),
(37, 'Camboya', 'Cambodia', 'Cambodge', 'KH', 'KHM', '855'),
(38, 'Camerún', 'Cameroon', 'Cameroun', 'CM', 'CMR', '237'),
(39, 'Canadá', 'Canada', 'Canada', 'CA', 'CAN', '1'),
(40, 'Chad', 'Chad', 'Tchad', 'TD', 'TCD', '235'),
(41, 'Chile', 'Chile', 'Chili', 'CL', 'CHL', '56'),
(42, 'China', 'China', 'Chine', 'CN', 'CHN', '86'),
(43, 'Chipre', 'Cyprus', 'Chypre', 'CY', 'CYP', '357'),
(44, 'Ciudad del Vaticano', 'Vatican City State', 'Cité du Vatican', 'VA', 'VAT', '39'),
(45, 'Colombia', 'Colombia', 'Colombie', 'CO', 'COL', '57'),
(46, 'Comoras', 'Comoros', 'Comores', 'KM', 'COM', '269'),
(47, 'República del Congo', 'Republic of the Congo', 'République du Congo', 'CG', 'COG', '242'),
(48, 'República Democrática del Congo', 'Democratic Republic of the Congo', 'République démocratique du Congo', 'CD', 'COD', '243'),
(49, 'Corea del Norte', 'North Korea', 'Corée du Nord', 'KP', 'PRK', '850'),
(50, 'Corea del Sur', 'South Korea', 'Corée du Sud', 'KR', 'KOR', '82'),
(51, 'Costa de Marfil', 'Ivory Coast', 'Côte-d\'Ivoire', 'CI', 'CIV', '225'),
(52, 'Costa Rica', 'Costa Rica', 'Costa Rica', 'CR', 'CRI', '506'),
(53, 'Croacia', 'Croatia', 'Croatie', 'HR', 'HRV', '385'),
(54, 'Cuba', 'Cuba', 'Cuba', 'CU', 'CUB', '53'),
(55, 'Curazao', 'Curaçao', 'Curaçao', 'CW', 'CWU', '5999'),
(56, 'Dinamarca', 'Denmark', 'Danemark', 'DK', 'DNK', '45'),
(57, 'Dominica', 'Dominica', 'Dominique', 'DM', 'DMA', '1 767'),
(58, 'Ecuador', 'Ecuador', 'Equateur', 'EC', 'ECU', '593'),
(59, 'Egipto', 'Egypt', 'Egypte', 'EG', 'EGY', '20'),
(60, 'El Salvador', 'El Salvador', 'El Salvador', 'SV', 'SLV', '503'),
(61, 'Emiratos Árabes Unidos', 'United Arab Emirates', 'Emirats Arabes Unis', 'AE', 'ARE', '971'),
(62, 'Eritrea', 'Eritrea', 'Erythrée', 'ER', 'ERI', '291'),
(63, 'Eslovaquia', 'Slovakia', 'Slovaquie', 'SK', 'SVK', '421'),
(64, 'Eslovenia', 'Slovenia', 'Slovénie', 'SI', 'SVN', '386'),
(65, 'España', 'Spain', 'Espagne', 'ES', 'ESP', '34'),
(66, 'Estados Unidos de América', 'United States of America', 'États-Unis d\'Amérique', 'US', 'USA', '1'),
(67, 'Estonia', 'Estonia', 'L\'Estonie', 'EE', 'EST', '372'),
(68, 'Etiopía', 'Ethiopia', 'Ethiopie', 'ET', 'ETH', '251'),
(69, 'Filipinas', 'Philippines', 'Philippines', 'PH', 'PHL', '63'),
(70, 'Finlandia', 'Finland', 'Finlande', 'FI', 'FIN', '358'),
(71, 'Fiyi', 'Fiji', 'Fidji', 'FJ', 'FJI', '679'),
(72, 'Francia', 'France', 'France', 'FR', 'FRA', '33'),
(73, 'Gabón', 'Gabon', 'Gabon', 'GA', 'GAB', '241'),
(74, 'Gambia', 'Gambia', 'Gambie', 'GM', 'GMB', '220'),
(75, 'Georgia', 'Georgia', 'Géorgie', 'GE', 'GEO', '995'),
(76, 'Ghana', 'Ghana', 'Ghana', 'GH', 'GHA', '233'),
(77, 'Gibraltar', 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '350'),
(78, 'Granada', 'Grenada', 'Grenade', 'GD', 'GRD', '1 473'),
(79, 'Grecia', 'Greece', 'Grèce', 'GR', 'GRC', '30'),
(80, 'Groenlandia', 'Greenland', 'Groenland', 'GL', 'GRL', '299'),
(81, 'Guadalupe', 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP', '590'),
(82, 'Guam', 'Guam', 'Guam', 'GU', 'GUM', '1 671'),
(83, 'Guatemala', 'Guatemala', 'Guatemala', 'GT', 'GTM', '502'),
(84, 'Guayana Francesa', 'French Guiana', 'Guyane française', 'GF', 'GUF', '594'),
(85, 'Guernsey', 'Guernsey', 'Guernesey', 'GG', 'GGY', '44'),
(86, 'Guinea', 'Guinea', 'Guinée', 'GN', 'GIN', '224'),
(87, 'Guinea Ecuatorial', 'Equatorial Guinea', 'Guinée Equatoriale', 'GQ', 'GNQ', '240'),
(88, 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'GW', 'GNB', '245'),
(89, 'Guyana', 'Guyana', 'Guyane', 'GY', 'GUY', '592'),
(90, 'Haití', 'Haiti', 'Haïti', 'HT', 'HTI', '509'),
(91, 'Honduras', 'Honduras', 'Honduras', 'HN', 'HND', '504'),
(92, 'Hong kong', 'Hong Kong', 'Hong Kong', 'HK', 'HKG', '852'),
(93, 'Hungría', 'Hungary', 'Hongrie', 'HU', 'HUN', '36'),
(94, 'India', 'India', 'Inde', 'IN', 'IND', '91'),
(95, 'Indonesia', 'Indonesia', 'Indonésie', 'ID', 'IDN', '62'),
(96, 'Irán', 'Iran', 'Iran', 'IR', 'IRN', '98'),
(97, 'Irak', 'Iraq', 'Irak', 'IQ', 'IRQ', '964'),
(98, 'Irlanda', 'Ireland', 'Irlande', 'IE', 'IRL', '353'),
(99, 'Isla Bouvet', 'Bouvet Island', 'Bouvet Island', 'BV', 'BVT', ''),
(100, 'Isla de Man', 'Isle of Man', 'Ile de Man', 'IM', 'IMN', '44'),
(101, 'Isla de Navidad', 'Christmas Island', 'Christmas Island', 'CX', 'CXR', '61'),
(102, 'Isla Norfolk', 'Norfolk Island', 'Île de Norfolk', 'NF', 'NFK', '672'),
(103, 'Islandia', 'Iceland', 'Islande', 'IS', 'ISL', '354'),
(104, 'Islas Bermudas', 'Bermuda Islands', 'Bermudes', 'BM', 'BMU', '1 441'),
(105, 'Islas Caimán', 'Cayman Islands', 'Iles Caïmans', 'KY', 'CYM', '1 345'),
(106, 'Islas Cocos (Keeling)', 'Cocos (Keeling) Islands', 'Cocos (Keeling', 'CC', 'CCK', '61'),
(107, 'Islas Cook', 'Cook Islands', 'Iles Cook', 'CK', 'COK', '682'),
(108, 'Islas de Åland', 'Åland Islands', 'Îles Åland', 'AX', 'ALA', '358'),
(109, 'Islas Feroe', 'Faroe Islands', 'Iles Féro', 'FO', 'FRO', '298'),
(110, 'Islas Georgias del Sur y Sandwich del Sur', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud', 'GS', 'SGS', '500'),
(111, 'Islas Heard y McDonald', 'Heard Island and McDonald Islands', 'Les îles Heard et McDonald', 'HM', 'HMD', ''),
(112, 'Islas Maldivas', 'Maldives', 'Maldives', 'MV', 'MDV', '960'),
(113, 'Islas Malvinas', 'Falkland Islands (Malvinas)', 'Iles Falkland (Malvinas', 'FK', 'FLK', '500'),
(114, 'Islas Marianas del Norte', 'Northern Mariana Islands', 'Iles Mariannes du Nord', 'MP', 'MNP', '1 670'),
(115, 'Islas Marshall', 'Marshall Islands', 'Iles Marshall', 'MH', 'MHL', '692'),
(116, 'Islas Pitcairn', 'Pitcairn Islands', 'Iles Pitcairn', 'PN', 'PCN', '870'),
(117, 'Islas Salomón', 'Solomon Islands', 'Iles Salomon', 'SB', 'SLB', '677'),
(118, 'Islas Turcas y Caicos', 'Turks and Caicos Islands', 'Iles Turques et Caïques', 'TC', 'TCA', '1 649'),
(119, 'Islas Ultramarinas Menores de Estados Unidos', 'United States Minor Outlying Islands', 'États-Unis Îles mineures éloignées', 'UM', 'UMI', '246'),
(120, 'Islas Vírgenes Británicas', 'Virgin Islands', 'Iles Vierges', 'VG', 'VGB', '1 284'),
(121, 'Islas Vírgenes de los Estados Unidos', 'United States Virgin Islands', 'Îles Vierges américaines', 'VI', 'VIR', '1 340'),
(122, 'Israel', 'Israel', 'Israël', 'IL', 'ISR', '972'),
(123, 'Italia', 'Italy', 'Italie', 'IT', 'ITA', '39'),
(124, 'Jamaica', 'Jamaica', 'Jamaïque', 'JM', 'JAM', '1 876'),
(125, 'Japón', 'Japan', 'Japon', 'JP', 'JPN', '81'),
(126, 'Jersey', 'Jersey', 'Maillot', 'JE', 'JEY', '44'),
(127, 'Jordania', 'Jordan', 'Jordan', 'JO', 'JOR', '962'),
(128, 'Kazajistán', 'Kazakhstan', 'Le Kazakhstan', 'KZ', 'KAZ', '7'),
(129, 'Kenia', 'Kenya', 'Kenya', 'KE', 'KEN', '254'),
(130, 'Kirguistán', 'Kyrgyzstan', 'Kirghizstan', 'KG', 'KGZ', '996'),
(131, 'Kiribati', 'Kiribati', 'Kiribati', 'KI', 'KIR', '686'),
(132, 'Kuwait', 'Kuwait', 'Koweït', 'KW', 'KWT', '965'),
(133, 'Líbano', 'Lebanon', 'Liban', 'LB', 'LBN', '961'),
(134, 'Laos', 'Laos', 'Laos', 'LA', 'LAO', '856'),
(135, 'Lesoto', 'Lesotho', 'Lesotho', 'LS', 'LSO', '266'),
(136, 'Letonia', 'Latvia', 'La Lettonie', 'LV', 'LVA', '371'),
(137, 'Liberia', 'Liberia', 'Liberia', 'LR', 'LBR', '231'),
(138, 'Libia', 'Libya', 'Libye', 'LY', 'LBY', '218'),
(139, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE', '423'),
(140, 'Lituania', 'Lithuania', 'La Lituanie', 'LT', 'LTU', '370'),
(141, 'Luxemburgo', 'Luxembourg', 'Luxembourg', 'LU', 'LUX', '352'),
(142, 'México', 'Mexico', 'Mexique', 'MX', 'MEX', '52'),
(143, 'Mónaco', 'Monaco', 'Monaco', 'MC', 'MCO', '377'),
(144, 'Macao', 'Macao', 'Macao', 'MO', 'MAC', '853'),
(145, 'Macedônia', 'Macedonia', 'Macédoine', 'MK', 'MKD', '389'),
(146, 'Madagascar', 'Madagascar', 'Madagascar', 'MG', 'MDG', '261'),
(147, 'Malasia', 'Malaysia', 'Malaisie', 'MY', 'MYS', '60'),
(148, 'Malawi', 'Malawi', 'Malawi', 'MW', 'MWI', '265'),
(149, 'Mali', 'Mali', 'Mali', 'ML', 'MLI', '223'),
(150, 'Malta', 'Malta', 'Malte', 'MT', 'MLT', '356'),
(151, 'Marruecos', 'Morocco', 'Maroc', 'MA', 'MAR', '212'),
(152, 'Martinica', 'Martinique', 'Martinique', 'MQ', 'MTQ', '596'),
(153, 'Mauricio', 'Mauritius', 'Iles Maurice', 'MU', 'MUS', '230'),
(154, 'Mauritania', 'Mauritania', 'Mauritanie', 'MR', 'MRT', '222'),
(155, 'Mayotte', 'Mayotte', 'Mayotte', 'YT', 'MYT', '262'),
(156, 'Micronesia', 'Estados Federados de', 'Federados Estados de', 'FM', 'FSM', '691'),
(157, 'Moldavia', 'Moldova', 'Moldavie', 'MD', 'MDA', '373'),
(158, 'Mongolia', 'Mongolia', 'Mongolie', 'MN', 'MNG', '976'),
(159, 'Montenegro', 'Montenegro', 'Monténégro', 'ME', 'MNE', '382'),
(160, 'Montserrat', 'Montserrat', 'Montserrat', 'MS', 'MSR', '1 664'),
(161, 'Mozambique', 'Mozambique', 'Mozambique', 'MZ', 'MOZ', '258'),
(162, 'Namibia', 'Namibia', 'Namibie', 'NA', 'NAM', '264'),
(163, 'Nauru', 'Nauru', 'Nauru', 'NR', 'NRU', '674'),
(164, 'Nepal', 'Nepal', 'Népal', 'NP', 'NPL', '977'),
(165, 'Nicaragua', 'Nicaragua', 'Nicaragua', 'NI', 'NIC', '505'),
(166, 'Niger', 'Niger', 'Niger', 'NE', 'NER', '227'),
(167, 'Nigeria', 'Nigeria', 'Nigeria', 'NG', 'NGA', '234'),
(168, 'Niue', 'Niue', 'Niou', 'NU', 'NIU', '683'),
(169, 'Noruega', 'Norway', 'Norvège', 'NO', 'NOR', '47'),
(170, 'Nueva Caledonia', 'New Caledonia', 'Nouvelle-Calédonie', 'NC', 'NCL', '687'),
(171, 'Nueva Zelanda', 'New Zealand', 'Nouvelle-Zélande', 'NZ', 'NZL', '64'),
(172, 'Omán', 'Oman', 'Oman', 'OM', 'OMN', '968'),
(173, 'Países Bajos', 'Netherlands', 'Pays-Bas', 'NL', 'NLD', '31'),
(174, 'Pakistán', 'Pakistan', 'Pakistan', 'PK', 'PAK', '92'),
(175, 'Palau', 'Palau', 'Palau', 'PW', 'PLW', '680'),
(176, 'Palestina', 'Palestine', 'La Palestine', 'PS', 'PSE', '970'),
(177, 'Panamá', 'Panama', 'Panama', 'PA', 'PAN', '507'),
(178, 'Papúa Nueva Guinea', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'PG', 'PNG', '675'),
(179, 'Paraguay', 'Paraguay', 'Paraguay', 'PY', 'PRY', '595'),
(180, 'Perú', 'Peru', 'Pérou', 'PE', 'PER', '51'),
(181, 'Polinesia Francesa', 'French Polynesia', 'Polynésie française', 'PF', 'PYF', '689'),
(182, 'Polonia', 'Poland', 'Pologne', 'PL', 'POL', '48'),
(183, 'Portugal', 'Portugal', 'Portugal', 'PT', 'PRT', '351'),
(184, 'Puerto Rico', 'Puerto Rico', 'Porto Rico', 'PR', 'PRI', '1'),
(185, 'Qatar', 'Qatar', 'Qatar', 'QA', 'QAT', '974'),
(186, 'Reino Unido', 'United Kingdom', 'Royaume-Uni', 'GB', 'GBR', '44'),
(187, 'República Centroafricana', 'Central African Republic', 'République Centrafricaine', 'CF', 'CAF', '236'),
(188, 'República Checa', 'Czech Republic', 'République Tchèque', 'CZ', 'CZE', '420'),
(189, 'República Dominicana', 'Dominican Republic', 'République Dominicaine', 'DO', 'DOM', '1 809'),
(190, 'República de Sudán del Sur', 'South Sudan', 'Soudan du Sud', 'SS', 'SSD', '211'),
(191, 'Reunión', 'Réunion', 'Réunion', 'RE', 'REU', '262'),
(192, 'Ruanda', 'Rwanda', 'Rwanda', 'RW', 'RWA', '250'),
(193, 'Rumanía', 'Romania', 'Roumanie', 'RO', 'ROU', '40'),
(194, 'Rusia', 'Russia', 'La Russie', 'RU', 'RUS', '7'),
(195, 'Sahara Occidental', 'Western Sahara', 'Sahara Occidental', 'EH', 'ESH', '212'),
(196, 'Samoa', 'Samoa', 'Samoa', 'WS', 'WSM', '685'),
(197, 'Samoa Americana', 'American Samoa', 'Les Samoa américaines', 'AS', 'ASM', '1 684'),
(198, 'San Bartolomé', 'Saint Barthélemy', 'Saint-Barthélemy', 'BL', 'BLM', '590'),
(199, 'San Cristóbal y Nieves', 'Saint Kitts and Nevis', 'Saint Kitts et Nevis', 'KN', 'KNA', '1 869'),
(200, 'San Marino', 'San Marino', 'San Marino', 'SM', 'SMR', '378'),
(201, 'San Martín (Francia)', 'Saint Martin (French part)', 'Saint-Martin (partie française)', 'MF', 'MAF', '1 599'),
(202, 'San Pedro y Miquelón', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'PM', 'SPM', '508'),
(203, 'San Vicente y las Granadinas', 'Saint Vincent and the Grenadines', 'Saint-Vincent et Grenadines', 'VC', 'VCT', '1 784'),
(204, 'Santa Elena', 'Ascensión y Tristán de Acuña', 'Ascensión y Tristan de Acuña', 'SH', 'SHN', '290'),
(205, 'Santa Lucía', 'Saint Lucia', 'Sainte-Lucie', 'LC', 'LCA', '1 758'),
(206, 'Santo Tomé y Príncipe', 'Sao Tome and Principe', 'Sao Tomé et Principe', 'ST', 'STP', '239'),
(207, 'Senegal', 'Senegal', 'Sénégal', 'SN', 'SEN', '221'),
(208, 'Serbia', 'Serbia', 'Serbie', 'RS', 'SRB', '381'),
(209, 'Seychelles', 'Seychelles', 'Les Seychelles', 'SC', 'SYC', '248'),
(210, 'Sierra Leona', 'Sierra Leone', 'Sierra Leone', 'SL', 'SLE', '232'),
(211, 'Singapur', 'Singapore', 'Singapour', 'SG', 'SGP', '65'),
(212, 'Sint Maarten', 'Sint Maarten', 'Saint-Martin', 'SX', 'SMX', '1 721'),
(213, 'Siria', 'Syria', 'Syrie', 'SY', 'SYR', '963'),
(214, 'Somalia', 'Somalia', 'Somalie', 'SO', 'SOM', '252'),
(215, 'Sri lanka', 'Sri Lanka', 'Sri Lanka', 'LK', 'LKA', '94'),
(216, 'Sudáfrica', 'South Africa', 'Afrique du Sud', 'ZA', 'ZAF', '27'),
(217, 'Sudán', 'Sudan', 'Soudan', 'SD', 'SDN', '249'),
(218, 'Suecia', 'Sweden', 'Suède', 'SE', 'SWE', '46'),
(219, 'Suiza', 'Switzerland', 'Suisse', 'CH', 'CHE', '41'),
(220, 'Surinám', 'Suriname', 'Surinam', 'SR', 'SUR', '597'),
(221, 'Svalbard y Jan Mayen', 'Svalbard and Jan Mayen', 'Svalbard et Jan Mayen', 'SJ', 'SJM', '47'),
(222, 'Swazilandia', 'Swaziland', 'Swaziland', 'SZ', 'SWZ', '268'),
(223, 'Tayikistán', 'Tajikistan', 'Le Tadjikistan', 'TJ', 'TJK', '992'),
(224, 'Tailandia', 'Thailand', 'Thaïlande', 'TH', 'THA', '66'),
(225, 'Taiwán', 'Taiwan', 'Taiwan', 'TW', 'TWN', '886'),
(226, 'Tanzania', 'Tanzania', 'Tanzanie', 'TZ', 'TZA', '255'),
(227, 'Territorio Británico del Océano Índico', 'British Indian Ocean Territory', 'Territoire britannique de l\'océan Indien', 'IO', 'IOT', '246'),
(228, 'Territorios Australes y Antárticas Franceses', 'French Southern Territories', 'Terres australes françaises', 'TF', 'ATF', ''),
(229, 'Timor Oriental', 'East Timor', 'Timor-Oriental', 'TL', 'TLS', '670'),
(230, 'Togo', 'Togo', 'Togo', 'TG', 'TGO', '228'),
(231, 'Tokelau', 'Tokelau', 'Tokélaou', 'TK', 'TKL', '690'),
(232, 'Tonga', 'Tonga', 'Tonga', 'TO', 'TON', '676'),
(233, 'Trinidad y Tobago', 'Trinidad and Tobago', 'Trinidad et Tobago', 'TT', 'TTO', '1 868'),
(234, 'Tunez', 'Tunisia', 'Tunisie', 'TN', 'TUN', '216'),
(235, 'Turkmenistán', 'Turkmenistan', 'Le Turkménistan', 'TM', 'TKM', '993'),
(236, 'Turquía', 'Turkey', 'Turquie', 'TR', 'TUR', '90'),
(237, 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TV', 'TUV', '688'),
(238, 'Ucrania', 'Ukraine', 'L\'Ukraine', 'UA', 'UKR', '380'),
(239, 'Uganda', 'Uganda', 'Ouganda', 'UG', 'UGA', '256'),
(240, 'Uruguay', 'Uruguay', 'Uruguay', 'UY', 'URY', '598'),
(241, 'Uzbekistán', 'Uzbekistan', 'L\'Ouzbékistan', 'UZ', 'UZB', '998'),
(242, 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VU', 'VUT', '678'),
(243, 'Venezuela', 'Venezuela', 'Venezuela', 'VE', 'VEN', '58'),
(244, 'Vietnam', 'Vietnam', 'Vietnam', 'VN', 'VNM', '84'),
(245, 'Wallis y Futuna', 'Wallis and Futuna', 'Wallis et Futuna', 'WF', 'WLF', '681'),
(246, 'Yemen', 'Yemen', 'Yémen', 'YE', 'YEM', '967'),
(247, 'Yibuti', 'Djibouti', 'Djibouti', 'DJ', 'DJI', '253'),
(248, 'Zambia', 'Zambia', 'Zambie', 'ZM', 'ZMB', '260'),
(249, 'Zimbabue', 'Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE', '263');
